name: Deploy to GCP
on:
  workflow_dispatch:
env:
  IMAGE: europe-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/web/arcane-web-proxy/nginx:1.21.6-alpine
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Google auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Authorize Docker push
        run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Push image to gcp artifact registry
        run: |-
          docker image build -t "$IMAGE" config
          docker image push "$IMAGE"
      - name: Deploy to GCP Cloud Run
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          BACKEND_ADDRESS: ${{ secrets.BACKEND_ADDRESS }}
          RESEARCH_UI_ADDRESS: ${{ secrets.RESEARCH_UI_ADDRESS }}
        run: |-
          gcloud run deploy arcane-web-proxy \
            --region europe-west1 \
            --image "$IMAGE" \
            --cpu=1 \
            --memory=512Mi \
            --min-instances=1 \
            --max-instances=1 \
            --concurrency=1000 \
            --set-env-vars=BACKEND_ADDRESS="$BACKEND_ADDRESS",RESEARCH_UI_ADDRESS="$RESEARCH_UI_ADDRESS",SERVER_DOMAIN_NAME=arcane.no,NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/ \
            --service-account arcane-web-proxy@"$GCP_PROJECT_ID".iam.gserviceaccount.com \
            --allow-unauthenticated \
            --port=8080 \
            --platform=managed
